=== TanguyHerbron/BTS/BTS/Web/Premiere annee/TD1XML/informatique.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT ordinateur (cm+, psu+, boitier+)>
<!ELEMENT cm (nom?, socket?, ram+, cpu+, gpu*)>
<!ATTLIST cm
    marque (ASRock|ASUS|EVGA|GygaByte|MSI|Autre) #REQUIRED
>
<!ELEMENT ram (marque?, nom?, frequence?, capacite?)>
<!ELEMENT cpu (nom?, frequence?, socket?)>
<!ATTLIST cpu
    marque (Intel|AMD|Autre) #REQUIRED
>
<!ELEMENT gpu (fabriquant?, marque?, nom?, frequence?, vram?)>
<!ELEMENT psu (marque?, nom?, puissance?, modulaire?, certification?)>
<!ELEMENT boitier (marque?, nom?, fenetre?)>
<!ELEMENT marque (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT socket (#PCDATA)>
<!ELEMENT frequence (#PCDATA)>
<!ELEMENT capacite (#PCDATA)>
<!ELEMENT fabriquant (#PCDATA)>
<!ELEMENT puissance (#PCDATA)>
<!ELEMENT modulaire (#PCDATA)>
<!ELEMENT certification (#PCDATA)>
<!ELEMENT fenetre (#PCDATA)>
<!ATTLIST __ROOT__ version CDATA #REQUIRED>

=== TanguyHerbron/BTS/BTS/Web/Premiere annee/TD1XML/informatique.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ordinateur SYSTEM "informatique.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ordinateur>
    <cm marque="MSI">
        <nom>z97 gaming 3</nom>
        <socket>1150</socket>
        <ram>
            <marque>Kingston</marque>
            <nom>HyperX Performance</nom>
            <frequence>1866 MHz</frequence>
            <capacite>16 Go</capacite>
        </ram>
        <cpu marque="Intel">
            <nom>I5 4690k</nom>
            <frequence>4.5 GHz</frequence>
            <socket>1150</socket>
        </cpu>
        <gpu>
            <fabriquant>NVidia</fabriquant>
            <marque>MSI</marque>
            <nom>GTX 970</nom>
            <frequence>1279 MHz</frequence>
        </gpu>
    </cm>
    <psu>
        <marque>Seasonic</marque>
        <nom>M12II</nom>
        <puissance>520W</puissance>
        <modulaire>Non</modulaire>
        <certification>80+ Bronze</certification>
    </psu>
    <boitier>
        <marque>Advance</marque>
        <nom>Dark Trooper</nom>
        <fenetre>Oui</fenetre>
    </boitier>
</ordinateur>
